# Generated by Django 4.2.6 on 2023-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillblankquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='fillblankquestion',
            name='correct_answers',
            field=models.TextField(default='test', verbose_name='answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fillblankquestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
