# Generated by Django 4.2.6 on 2023-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_fillblankquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillblankquestion',
            name='correct_answers',
            field=models.CharField(max_length=255),
        ),
    ]
