# Generated by Django 4.2.6 on 2023-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_rename_correct_answers_fillblankquestion_correct_answers_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='option_four',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theory_text',
            field=models.CharField(max_length=10000),
        ),
    ]
