# Generated by Django 4.2.6 on 2023-10-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_multiplechoicequestion_option_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='fill_blank_task',
            field=models.CharField(default='fill_blank_task', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='multiple_choice_task',
            field=models.CharField(default='multiple_choice_task', max_length=100),
        ),
    ]
