# Generated by Django 4.2.6 on 2023-10-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_fill_blank_task_lesson_multiple_choice_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fill_blank_task',
            field=models.CharField(blank=True, default='fill_blank_task', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='multiple_choice_task',
            field=models.CharField(blank=True, default='multiple_choice_task', max_length=100),
        ),
    ]
