# Generated by Django 4.2.6 on 2023-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_fill_blank_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_text_theory', models.CharField(max_length=250)),
                ('phrase_text_win', models.CharField(max_length=250)),
                ('phrase_text_defeat', models.CharField(max_length=250)),
            ],
        ),
    ]
