# Generated by Django 4.2.6 on 2023-10-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_phrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='phrase_text_defeat',
            new_name='text_defeat',
        ),
        migrations.RenameField(
            model_name='phrase',
            old_name='phrase_text_theory',
            new_name='text_theory',
        ),
        migrations.RenameField(
            model_name='phrase',
            old_name='phrase_text_win',
            new_name='text_win',
        ),
    ]
