# Generated by Django 4.2.6 on 2023-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_rename_phrase_text_defeat_phrase_text_defeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='name',
            field=models.CharField(default='win', max_length=100),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='text_defeat',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='text_theory',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='text_win',
            field=models.CharField(max_length=500),
        ),
    ]
