# Generated by Django 4.2.6 on 2023-10-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_phrase_name_alter_phrase_text_defeat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='text_defeat',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='text_theory',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='text_win',
        ),
    ]
