version: '3'

services:
  redis:
    build:
      context: ./backend
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    networks:
      - babylon_network

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - babylon_network

  daphne:
    build:
      context: ./backend
      dockerfile: Dockerfile.daphne
    ports:
      - "8443:8443"
    depends_on:
      - redis
    networks:
      - babylon_network
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - web
      networks:
        - babylon_network

networks:
  babylon_network:
    external: true
